name = "bestyjs-worker"
type = "javascript"
workers_dev = false

compatibility_date = "2021-12-10"
compatibility_flags = []

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"

[env.production]
zone_id = "71470a7b9ca059ee006ceb87cda2ee5b"
account_id = "9b9cf6c060da03186bb4b618460149e0"
route = "api.bestyjs.com/*"
