name: Compile and lint code

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  compile-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read nvmrc
        id: read-nvmrc
        run: echo "::set-output name=version::$(cat .nvmrc)"
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.read-nvmrc.outputs.version }}y

      - name: Install modules
        run: yarn
      - name: Check fmt
        run: yarn fmt:check
