name: Compile and lint code

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  compile-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Install modules
        run: yarn
      - name: Check fmt
        run: yarn fmt:check
